"""Report generation: self-contained, printable HTML with revision stamp."""

from datetime import datetime
from html import escape


def _row(r):
    status = "PASS" if r.ok else "FAIL"
    cls = "ok" if r.ok else "fail"
    smin = f"{r.smin_scc_mm2:.1f}" if r.smin_scc_mm2 else "-"
    return f"""
      <tr class="{cls}">
        <td>{escape(r.tag)}</td>
        <td>{r.ib_a:.1f}</td>
        <td>{r.iz_required_a:.1f}</td>
        <td>{r.ca:.2f} / {r.cg:.2f}</td>
        <td>{r.size_mm2:g}</td>
        <td>{r.iz_table_a:.0f}</td>
        <td>{r.vd_pct:.2f}</td>
        <td>{smin}</td>
        <td class="status">{status}</td>
      </tr>"""


def render_html(results, *, project="Untitled project", revision="A",
                author="", standard="IEC 60364-5-52"):
    stamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    rows = "".join(_row(r) for r in results)
    n_fail = sum(1 for r in results if not r.ok)
    summary = (f'<span class="fail">{n_fail} cable(s) FAIL</span>'
               if n_fail else '<span class="ok">All cables PASS</span>')
    notes = []
    for r in results:
        for n in r.notes:
            notes.append(f"<li><b>{escape(r.tag)}:</b> {escape(n)}</li>")
    notes_html = f"<ul>{''.join(notes)}</ul>" if notes else "<p>None.</p>"

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>Cable Calculation Report - {escape(project)} (Rev {escape(revision)})</title>
<style>
  body {{ font-family: Arial, Helvetica, sans-serif; color:#1a1a1a; margin:32px; }}
  h1 {{ font-size:20px; margin-bottom:0; }}
  .meta {{ color:#555; font-size:12px; margin:4px 0 18px; }}
  table {{ border-collapse:collapse; width:100%; font-size:12px; }}
  th, td {{ border:1px solid #ccc; padding:6px 8px; text-align:right; }}
  th {{ background:#f0f3f7; text-align:center; }}
  td:first-child {{ text-align:left; }}
  .status {{ font-weight:bold; }}
  tr.fail td {{ background:#fdeaea; }}
  .ok {{ color:#1a7f37; font-weight:bold; }}
  .fail {{ color:#c1121f; font-weight:bold; }}
  .disclaimer {{ margin-top:24px; font-size:11px; color:#777;
                 border-top:1px solid #ddd; padding-top:10px; }}
</style></head><body>
  <h1>Cable Calculation Report</h1>
  <div class="meta">
    Project: <b>{escape(project)}</b> &nbsp;|&nbsp; Revision: <b>{escape(revision)}</b>
    &nbsp;|&nbsp; Standard: {escape(standard)}<br>
    Prepared by: {escape(author or 'n/a')} &nbsp;|&nbsp; Generated: {stamp} &nbsp;|&nbsp;
    Result: {summary}
  </div>
  <table>
    <thead><tr>
      <th>Cable tag</th><th>Ib (A)</th><th>Iz' req (A)</th><th>Ca / Cg</th>
      <th>Size (mm2)</th><th>Iz table (A)</th><th>VD (%)</th>
      <th>S<sub>min</sub> SC (mm2)</th><th>Status</th>
    </tr></thead>
    <tbody>{rows}</tbody>
  </table>
  <h3 style="font-size:13px;">Notes</h3>
  {notes_html}
  <div class="disclaimer">
    Generated by CableCalc MVP. Ampacity dataset is a representative subset of
    {escape(standard)} for Cu/XLPE. This report does not constitute a certified
    design; verify against the applicable standard edition and manufacturer data.
  </div>
</body></html>"""


def render_markdown(results, *, project="Untitled project", revision="A"):
    lines = [f"# Cable Calculation Report - {project} (Rev {revision})", ""]
    lines.append("| Tag | Ib (A) | Iz' req (A) | Ca | Cg | Size mm2 | Iz (A) | VD % | Smin SC | Status |")
    lines.append("|---|---|---|---|---|---|---|---|---|---|")
    for r in results:
        smin = f"{r.smin_scc_mm2:.1f}" if r.smin_scc_mm2 else "-"
        lines.append(
            f"| {r.tag} | {r.ib_a:.1f} | {r.iz_required_a:.1f} | {r.ca:.2f} | "
            f"{r.cg:.2f} | {r.size_mm2:g} | {r.iz_table_a:.0f} | {r.vd_pct:.2f} | "
            f"{smin} | {'PASS' if r.ok else 'FAIL'} |"
        )
    return "\n".join(lines) + "\n"
